name: BuxFriends2
version: ${project.version}
main: com.github.letsgoridepandas.buxfriends2.BuxFriends2
api-version: 1.17
authors: [ LetsGoRidePandas ]
description: Friends Plugin
depend: [Vault]

commands:
  f:
    description: BuxFriends Usage
    usage: /friends
    permission: buxfriends.list
    permission-message: You don't have permission to use a Friends!
  friend:
    description: BuxFriends Usage
    usage: /friends
    permission: buxfriends.list
    permission-message: You don't have permission to use a Friends!
  friends:
    description: BuxFriends Usage
    usage: /friends
    permission: buxfriends.list
    permission-message: You don't have permission to use a Friends!
